# Generated by Django 6.0.2 on 2026-03-16 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LemonSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, default='', max_length=120)),
                ('subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('admin_unlocked', models.BooleanField(default=False)),
                ('extra_daily_quota', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lemon_sub', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('plays', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'user'], name='main_dailyu_date_b8b7f0_idx'), models.Index(fields=['date', 'guest_id'], name='main_dailyu_date_47a934_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('guest_id__isnull', True)), models.Q(('user__isnull', True), ('guest_id__isnull', False), models.Q(('guest_id', ''), _negated=True)), _connector='OR'), name='ck_dailyusage_user_xor_guest'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'date'), name='uniq_dailyusage_user_date'), models.UniqueConstraint(condition=models.Q(('user__isnull', True), ('guest_id__isnull', False), models.Q(('guest_id', ''), _negated=True)), fields=('guest_id', 'date'), name='uniq_dailyusage_guest_date')],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('final_capital', models.FloatField(default=0)),
                ('score_total', models.IntegerField(db_index=True, default=0)),
                ('score_asset', models.IntegerField(default=0)),
                ('score_risk', models.IntegerField(default=0)),
                ('turns_used', models.IntegerField(default=0)),
                ('max_lev', models.IntegerField(default=1)),
                ('max_bet_pct', models.IntegerField(default=0)),
                ('event_turns', models.IntegerField(default=0)),
                ('dangerous_exposures', models.IntegerField(default=0)),
                ('timeouts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['score_total', 'final_capital', 'created_at'], name='main_leader_score_t_80342f_idx'), models.Index(fields=['user', 'created_at'], name='main_leader_user_id_8b4711_idx')],
            },
        ),
    ]
