# Generated by Django 6.0.1 on 2026-03-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='login_id_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='nickname_snapshot',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='provider_snapshot',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
