# Generated by Django 6.0.1 on 2026-03-18 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_leaderboardentry_login_id_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['-score_total', '-final_capital', '-created_at']},
        ),
        migrations.CreateModel(
            name='GlobalTurnEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('bonus_turns', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('members_only', models.BooleanField(default=False)),
                ('paid_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'start_at', 'end_at'], name='main_global_is_acti_557481_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTurnBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('bonus_turns', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='main_usertu_user_id_7fc9fe_idx'), models.Index(fields=['user', 'start_at', 'end_at'], name='main_usertu_user_id_f5f05d_idx')],
            },
        ),
    ]
