# Generated by Django 6.0.1 on 2026-03-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
